[package]
name = "day3"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
glam = { workspace = true }
itertools.workspace = true
nom = { workspace = true }
nom_locate = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
